### ISSUE TITLE
Logger name override

### ISSUE THREAD

**Issue by nradtke** [tanghaibao/pybind11_log#4]
Currently the logger name appears to be hardcoded to `pybind11_log`.  Can we get a way to override this?  My project has multiple modules that all use this library to facilitate logging, but with the hardcoded logger name, it makes it difficult to tell which module it's coming from.

**Comment by tanghaibao** [comment]
@nradtke 

Thanks for the suggestion. You can now pass in the logger name. For example:

```
pybind11_log::init_mt(logger_name);
```

Please let me know if it's not working for you.

**Comment by nradtke** [comment]
I've integrated this into my codebase and it's working as expected in the multi-threaded case.  Admittedly did not try the single-thread version.
